### ISSUE TITLE
Live partial output

### ISSUE THREAD

**Issue by int-index** [emilaxelsson/trackit#2]
`trackit` provides no feedback while a command is running. I tried using it to run `cabal`:

```
trackit -t src/ -c "cabal v2-build"
```

But it's not convenient at all as I see no indication of progress while the command is running (which takes about 5 seconds in the project I tested).

**Comment by emilaxelsson** [comment]
That's a good suggestion. I also experienced this when using it with Cabal.
I'll have to think about what's the best way to do this.

**Comment by emilaxelsson** [comment]
I've pushed a version on a [branch](https://github.com/emilaxelsson/trackit/tree/issue-2-partial-output) that shows a small notification message while the command is running. I had to restructure the program and move the system call to a separate process, so as a bonus the GUI is now responsible even when the command is running (e.g. you can scroll in the existing buffer).

But since the issue title says "partial output", I'm guessing that you actually want to see the command output updated line by line. I'll look into making that work.

**Comment by emilaxelsson** [comment]
There are now two new flags:

```
  -r,--show-running        Display a message while the command is running.
  -i,--incremental         Allow output to be updated incrementally. Redraws the
                           buffer for every output line, so should only be used
                           for slow outputs. Implies '--show-running'.
```

The reason for introducing these flags instead of just having them on is:

  * As said above, `--incremental` slows down the drawing. I think we'd need support for incremental output in Brick in order to solve this. I don't know if something like that exists.
  * Even `--show-running` causes a flicker that I prefer not to see for commands that return instantaneously.

**Comment by emilaxelsson** [comment]
@int-index does this work for you?

**Comment by int-index** [comment]
@emilaxelsson Yes, that's very nice. The only thing that bothers me is that because of the "Command running" badge, the first line of the output is not visible. Can it be displayed at the end similarly to the "End of output" terminator?

So while the command is running, it would say

```
---------- Command running ----------
```

and then become

```
----------- End of output -----------
```

**Comment by int-index** [comment]
Thank you!

**Comment by int-index** [comment]
Here's what I mean:

![image](https://user-images.githubusercontent.com/4061728/51268720-caa23c80-19d1-11e9-80c2-27a2f8ba3cd6.png)

This `s...` on the first line looks a bit out of place, because in reality it's "Resolving dependencies..." overlayed by "Command running".

**Comment by emilaxelsson** [comment]
Yeah, I agree, and I like your suggestion. Will fix that.

**Comment by emilaxelsson** [comment]
OK, can you see if it works as desired now?

I also added a flag that I think can be useful in your situation:

```
  -f,--follow-tail         Follow the tail of the generated output.
```

**Comment by int-index** [comment]
Thank you, it works great.
