### ISSUE TITLE
stdout/stderr

### ISSUE THREAD

**Issue by int-index** [emilaxelsson/trackit#3]
By default, `trackit` does not display `stderr`. This means I have to run

```
trackit -i -t src/ -c "cabal v2-build 2>&1"
```

rather than

```
trackit -i -t src/ -c "cabal v2-build"
```

I'm not sure if this is by design, but initially I was confused why I wasn't seeing build errors.

**Comment by emilaxelsson** [comment]
It's not by design, but I'm not sure how to properly add `stderr` to the output. The command I'm using from [`process-extras`](https://hackage.haskell.org/package/process-extras/docs/System-Process-Text.html#v:readCreateProcessWithExitCode) returns the streams as separate values, whereas `2>&1` will interleave the streams (AFAIK?).

Maybe I could show `stderr` if it's non-empty and otherwise show `stdout`. What do you think?

**Comment by int-index** [comment]
> Maybe I could show `stderr` if it's non-empty and otherwise show `stdout`. What do you think?

Yes, that'd work great for my use case, but probably not in general.

From https://stackoverflow.com/questions/6736790/how-can-i-combine-handles-in-haskell it seems there's no easy way to interleave these streams, unfortunately.

I think adding the `2>&1` workaround to `README` would be sufficient.

**Comment by emilaxelsson** [comment]
I've updated the README. Thanks!
